AWSTemplateFormatVersion: 2010-09-09
Description: template to deploy application loadbalancer along with autoscaling and launch configuration. 

Resources:
        
  LoadBalancerWordPressSite:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Tags: 
        - 
          Key: "Name"
          Value: "Client1"
      Subnets:
          - subnet-4ba4ec2d
          - subnet-4ce27716
          - subnet-69560d21
      SecurityGroups:
          - sg-068ecc2d65346af3d
      Scheme: internet-facing

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancerWordPressSite
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LoadBalancerWordPressSite
    Properties:
      VpcId: vpc-4b504e2d
      HealthCheckPort: 80
      Port: 80
      Protocol: HTTP
      Matcher:
           HttpCode: 200
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /healthy.html
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      TargetType: "instance"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  LoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
             - /
      Actions:
        - TargetGroupArn: !Ref LoadBalancerTargetGroup
          Type: forward

  ASGWordPress: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
       - eu-west-1c
       - eu-west-1b
      LaunchConfigurationName: 
       Ref: "LaunchConfigWordPress"
      MinSize: "2"
      MaxSize: "2"
      TargetGroupARNs: 
       - !Ref LoadBalancerTargetGroup
      Tags: 
        - Key: Name
          PropagateAtLaunch: Yes
          Value: WordPressSite1
       
  LaunchConfigWordPress: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      KeyName: aviral2k19key
      ImageId: ami-0aea3b18482ff8d2b
      SecurityGroups: 
        - sg-068ecc2d65346af3d
      InstanceType: "t2.micro"

Outputs:
  LoadBalancerDNS:
    Description: Application Loadbalancer Used For Wordpress Site 
    Value: !GetAtt LoadBalancerWordPressSite.DNSName
    Export:
        Name:
          Fn::Sub: "${AWS::StackName}-dns"